services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: 1
      PMA_HOSTS: distribuidora_db,gotas_db
    ports:
      - "127.0.0.1:8080:80"
