server {
    listen 80;
    server_name distribuidoraglavas.com www.distribuidoraglavas.com distribuidora.local;

    location / {
        proxy_pass http://distribuidora_web:80;
    }
}

server {
    listen 80;
    server_name gotasdecristal.com www.gotasdecristal.com gotas.local;

    location / {
        proxy_pass http://gotas_web:80;
    }
}
